backend:
  name: git-gateway
  branch: master

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    delete: true
    extension: "md"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Role", name: "authorRole", widget: "string"}
      - {label: "Publish Date", name: "publishDate", widget: "datetime"}
      - {label: "Image", name: "image", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["zdraví"]}
      - {label: "Body", name: "body", widget: "markdown"}